export * from './Create'
export * from './what'
export * from './Dashboard'
export * from './Settings'
export * from './SwipeIndex'
export * from './EditSingleSwipe'
export * from './SingleSwipe'
export * from './Tags'